DROP TABLE IF EXISTS USUARIOS;
DROP TABLE IF EXISTS PROJETOS;
DROP TABLE IF EXISTS USUARIOS_PROJETOS;
DROP TABLE IF EXISTS HORAS_APONTADAS;

CREATE TABLE USUARIOS
(
  MATRICULA_USUARIO INT AUTO_INCREMENT  PRIMARY KEY,
  NOME_USUARIO VARCHAR(250) NOT NULL
);

INSERT INTO USUARIOS (NOME_USUARIO) VALUES
    ('Administrador'),
    ('Programador 1'),
    ('Programador 2');

CREATE TABLE PROJETOS
(
  ID_PROJETO INT AUTO_INCREMENT  PRIMARY KEY,
  NOME_PROJETO VARCHAR(250) NOT NULL
);

INSERT INTO PROJETOS (NOME_PROJETO) VALUES
    ('Projeto Cliente A'),
    ('Projeto Cliente B');

CREATE TABLE USUARIOS_PROJETOS
(
  MATRICULA_USUARIO INT(10) NOT NULL ,
  ID_PROJETO INT(10) NOT NULL,
  FOREIGN KEY(MATRICULA_USUARIO) REFERENCES USUARIOS,
  FOREIGN KEY(ID_PROJETO) REFERENCES PROJETOS
);

INSERT INTO USUARIOS_PROJETOS (MATRICULA_USUARIO,ID_PROJETO) values
    (2,1),
    (3,1),
    (3,2);

CREATE TABLE HORAS_APONTADAS
(
  MATRICULA_USUARIO INT(10) NOT NULL ,
  ID_PROJETO INT(10) NOT NULL,
  HORAS_APONTADAS VARCHAR2(5),
  DATA_DO_LACAMENTO DATE
)


